### PR TITLE
New version of index builders

### PR DESCRIPTION
**Pull request by fmeheust**
This branch add the possibility to specify how the vector index should be create (type and parameters) and to create function based indexes on the metadata column.

### CODE REVIEW

**Comment by Michael-A-McMahon** [comment]
Any thoughts about making the API more consistent with that of EmbeddingTable?
Example:
```java
OracleEmbeddingStore.builder()
  .vectorIndex(IVFIndex.builder() // <-- Returns an IVFIndex.Builder object
    .createOption(CREATE_OR_REPLACE)
    .build()) // <-- Returns an IVFIndex object
  ...
```
If our API for indexes is similar to that of tables, it will make it easier for users to learn and use: If they know how to configure a table, they can transfer that knowledge to configuring an index. In the current commit, the API for indexes is very different from that of tables.

**Comment by fmeheust** [comment]
> Any thoughts about making the API more consistent with that of EmbeddingTable? Example:
> 
> ```java
> OracleEmbeddingStore.builder()
>   .vectorIndex(IVFIndex.builder() // <-- Returns an IVFIndex.Builder object
>     .createOption(CREATE_OR_REPLACE)
>     .build()) // <-- Returns an IVFIndex object
>   ...
> ```
> 
> If our API for indexes is similar to that of tables, it will make it easier for users to learn and use: If they know how to configure a table, they can transfer that knowledge to configuring an index. In the current commit, the API for indexes is very different from that of tables.

How would you pass the embedding table to the index in that case ? Would you declare the table first and then pass it to the store and the index ? The index needs to know the table (name and columns). If we create the index after the store has been created we could have:

```java
IVFIndex.builder()
    // either this line
    .store(oracleEmbeddingStore)
    // or this one
    .embeddingTable(embeddingTable)
    .createOption(CREATE_OR_REPLACE)
    .build();
```

**Comment by Michael-A-McMahon** [comment]
> > Any thoughts about making the API more consistent with that of EmbeddingTable? Example:
> > ```java
> > OracleEmbeddingStore.builder()
> >   .vectorIndex(IVFIndex.builder() // <-- Returns an IVFIndex.Builder object
> >     .createOption(CREATE_OR_REPLACE)
> >     .build()) // <-- Returns an IVFIndex object
> >   ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If our API for indexes is similar to that of tables, it will make it easier for users to learn and use: If they know how to configure a table, they can transfer that knowledge to configuring an index. In the current commit, the API for indexes is very different from that of tables.
> 
> How would you pass the embedding table to the index in that case ? Would you declare the table first and then pass it to the store and the index ? The index needs to know the table (name and columns).

Now I see the rationale! What if we had a `VectorIndex.create(EmbeddingTable)` method? This method gets called from the constructor of OracleEmbeddingStore. The constructor of OracleEmbeddingStore has all the pieces of the puzzle, the EmbeddingTable + VectorIndex, so this where the composition can happen.

**Comment by fmeheust** [comment]
> > > Any thoughts about making the API more consistent with that of EmbeddingTable? Example:
> > > ```java
> > > OracleEmbeddingStore.builder()
> > >   .vectorIndex(IVFIndex.builder() // <-- Returns an IVFIndex.Builder object
> > >     .createOption(CREATE_OR_REPLACE)
> > >     .build()) // <-- Returns an IVFIndex object
> > >   ...
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > If our API for indexes is similar to that of tables, it will make it easier for users to learn and use: If they know how to configure a table, they can transfer that knowledge to configuring an index. In the current commit, the API for indexes is very different from that of tables.
> > 
> > 
> > How would you pass the embedding table to the index in that case ? Would you declare the table first and then pass it to the store and the index ? The index needs to know the table (name and columns).
> 
> Now I see the rationale! What if we had a `VectorIndex.create(EmbeddingTable)` method? This method gets called from the constructor of OracleEmbeddingStore. The constructor of OracleEmbeddingStore has all the pieces of the puzzle, the EmbeddingTable + VectorIndex, so this where the composition can happen.

That would be possible, but in that case we no longer have builders, since they don't actually build anything and the build() method becomes useless. And some times of indexes should be created after the store has be populated, so calling the create() method in the constructor can be too early. I am assuming that the store would be a bean that gets created ones.

**Pull request closed without merging**
